remote_theme: just-the-docs/just-the-docs
title: Microsoft Azure Tutorial
description: Microsoft Azure Presentation and Tutorial

aux_links:
  "Click Here For The Presentation: ":
  - "https://b00346531.github.io/Page1"
